### ISSUE TITLE
Guest Permissions

### ISSUE THREAD

**Issue by riacoding** [mtliendo/simple-knowledge-base#1]
I loved this demo. I struggled a little with the permissions as unauth users couldn't access the LLM so I switched default auth back to apiKey. Also my usual region is us-west-1 and so I was coming up against the IAM role permissions for the model in us-east-1. I have PR ready to go with a parametrized region and a minor UI loading change/readme. Happy to submit if you want. Thanks again for this!!

**Comment by mtliendo** [comment]
Thanks for much for checking it out! PR's are definitely welcome :) Looking forward to reviewing it!
